
version: 2

models:
    - name: match-results_raw
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            #tests:
            #    - unique
            #    - not_null
            
    - name: album-releases
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            #tests:
            #    - unique
            #    - not_null
    - name: match-results
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            #tests:
            #    - unique
            #    - not_null
    - name: master-table-raw
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            #tests:
            #    - unique
            #    - not_null
    - name: master-table
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            #tests:
            #    - unique
            #    - not_null

    - name: pivot-table
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            #tests:
            #    - unique
            #    - not_null
